class DetectorConfig {
  final double thresholdMedium;
  final double thresholdHigh;

  final double weightShortUrl;
  final double weightOtp;
  final double weightUrgency;
  final double weightBankKeyword;
  final double weightSuspectSender;
  final double weightInCallOtpBoost;

  // Additional per-signal weights for specific scam patterns.
  final double weightPaymentRequest;
  final double weightRewardScam;
  final double weightParcelScam;
  final double weightCryptoScam;

  final List<String> shortUrlDomains;
  final List<String> urgencyKeywords;
  final List<String> bankKeywords;
  final List<String> suspectSenderPatterns;
  final List<String> otpKeywords;
  final List<String> paymentRequestKeywords;
  final List<String> rewardScamKeywords;
  final List<String> parcelScamKeywords;
  final List<String> cryptoScamKeywords;

  const DetectorConfig({
    required this.thresholdMedium,
    required this.thresholdHigh,
    required this.weightShortUrl,
    required this.weightOtp,
    required this.weightUrgency,
    required this.weightBankKeyword,
    required this.weightSuspectSender,
    required this.weightInCallOtpBoost,
    required this.weightPaymentRequest,
    required this.weightRewardScam,
    required this.weightParcelScam,
    required this.weightCryptoScam,
    required this.shortUrlDomains,
    required this.urgencyKeywords,
    required this.bankKeywords,
    required this.suspectSenderPatterns,
    required this.otpKeywords,
    required this.paymentRequestKeywords,
    required this.rewardScamKeywords,
    required this.parcelScamKeywords,
    required this.cryptoScamKeywords,
  });

  factory DetectorConfig.defaults() {
    return DetectorConfig(
      thresholdMedium: 0.4,
      thresholdHigh: 0.7,
      weightShortUrl: 0.25,
      weightOtp: 0.25,
      weightUrgency: 0.20,
      weightBankKeyword: 0.20,
      weightSuspectSender: 0.10,
      weightInCallOtpBoost: 0.35,
      weightPaymentRequest: 0.20,
      weightRewardScam: 0.15,
      weightParcelScam: 0.15,
      weightCryptoScam: 0.15,
      shortUrlDomains: const [
        'bit.ly',
        'tinyurl.com',
        'goo.gl',
        't.co',
        'ow.ly',
        'is.gd',
        'buff.ly',
        'adf.ly',
        'short.io',
        'rb.gy',
        'cutt.ly',
        'tiny.cc',
        'snip.ly',
        'rebrand.ly',
        'soo.gd',
        'lnkd.in',
        'bl.ink',
        'shorte.st',
        'clk.im',
        'mcaf.ee',
      ],
      urgencyKeywords: const [
        // English
        'urgent',
        'immediately',
        'suspended',
        'blocked',
        'action required',
        'your account will be',
        'click now',
        'verify now',
        'limited time',
        'expire',
        'final notice',
        'legal action',
        'arrested',
        'penalty',
        'act now',
        'last chance',
        'warning:',
        'alert:',
        'fraud alert',
        'court notice',
        'tax penalty',
        'customs issue',
        'delivery failed',
        'payment pending',
        'security alert',
        'unauthorized access',
        'update immediately',
        'account locked',
        'suspicious activity detected',
        // Hindi
        'तत्काल',
        'तुरंत',
        'निलंबित',
        'कार्रवाई आवश्यक',
        'आपका खाता बंद हो जाएगा',
        'अभी क्लिक करें',
        'अभी सत्यापित करें',
        'सीमित समय',
        'अंतिम सूचना',
        'कानूनी कार्रवाई',
        'जुर्माना',
        'अभी कार्य करें',
        'अंतिम अवसर',
        'धोखाधड़ी अलर्ट',
        'कोर्ट नोटिस',
        'खाता लॉक',
        'संदिग्ध गतिविधि',
        'सुरक्षा अलर्ट',
        'अनधिकृत पहुंच',
        'तुरंत अपडेट करें',
        // Bengali
        'জরুরি',
        'অবিলম্বে',
        'স্থগিত',
        'ব্যবস্থা প্রয়োজন',
        'আপনার অ্যাকাউন্ট বন্ধ হয়ে যাবে',
        'এখনই ক্লিক করুন',
        'এখনই যাচাই করুন',
        'সীমিত সময়',
        'চূড়ান্ত নোটিশ',
        'আইনি ব্যবস্থা',
        'জরিমানা',
        'এখনই কাজ করুন',
        'শেষ সুযোগ',
        'জালিয়াতি সতর্কতা',
        'আদালতের নোটিশ',
        'অ্যাকাউন্ট লক',
        'সন্দেহজনক কার্যকলাপ',
        'নিরাপত্তা সতর্কতা',
        // Tamil
        'அவசரம்',
        'உடனடியாக',
        'நிறுத்தப்பட்டது',
        'நடவடிக்கை தேவை',
        'உங்கள் கணக்கு நிறுத்தப்படும்',
        'இப்போது கிளிக் செய்யுங்கள்',
        'இப்போது சரிபார்க்கவும்',
        'இறுதி அறிவிப்பு',
        'சட்ட நடவடிக்கை',
        'அபராதம்',
        'கடைசி வாய்ப்பு',
        'மோசடி எச்சரிக்கை',
        'நீதிமன்ற அறிவிப்பு',
        'கணக்கு பூட்டப்பட்டது',
        'சந்தேகமான செயல்பாடு',
        'பாதுகாப்பு எச்சரிக்கை',
        // Telugu
        'అత్యవసరం',
        'వెంటనే',
        'సస్పెండ్ చేయబడింది',
        'చర్య అవసరం',
        'మీ ఖాతా నిలిపివేయబడుతుంది',
        'ఇప్పుడే క్లిక్ చేయండి',
        'ఇప్పుడే ధృవీకరించండి',
        'చివరి నోటీసు',
        'చట్టపరమైన చర్య',
        'జరిమానా',
        'చివరి అవకాశం',
        'మోసం హెచ్చరిక',
        'కోర్టు నోటీసు',
        'ఖాతా లాక్',
        'అనుమానాస్పద కార్యకలాపం',
        'భద్రత హెచ్చరిక',
        // Kannada
        'ತುರ್ತು',
        'ತಕ್ಷಣ',
        'ಅಮಾನತು',
        'ಕ್ರಮ ಅಗತ್ಯ',
        'ನಿಮ್ಮ ಖಾತೆ ನಿಲ್ಲಿಸಲಾಗುತ್ತದೆ',
        'ಈಗ ಕ್ಲಿಕ್ ಮಾಡಿ',
        'ಈಗ ಪರಿಶೀಲಿಸಿ',
        'ಅಂತಿಮ ಸೂಚನೆ',
        'ಕಾನೂನು ಕ್ರಮ',
        'ದಂಡ',
        'ಕೊನೆಯ ಅವಕಾಶ',
        'ವಂಚನೆ ಎಚ್ಚರಿಕೆ',
        'ನ್ಯಾಯಾಲಯ ನೋಟಿಸ್',
        'ಖಾತೆ ಲಾಕ್',
        'ಸಂಶಯಾಸ್ಪದ ಚಟುವಟಿಕೆ',
        'ಭದ್ರತಾ ಎಚ್ಚರಿಕೆ',
        // Malayalam
        'അടിയന്തരം',
        'ഉടൻ',
        'സസ്പെൻഡ് ചെയ്തു',
        'നടപടി ആവശ്യം',
        'നിങ്ങളുടെ അക്കൗണ്ട് സസ്പെൻഡ് ചെയ്യും',
        'ഇപ്പോൾ ക്ലിക്ക് ചെയ്യുക',
        'ഇപ്പോൾ പരിശോധിക്കുക',
        'അന്തിമ നോട്ടീസ്',
        'നിയമ നടപടി',
        'പിഴ',
        'അവസാന അവസരം',
        'തട്ടിപ്പ് മുന്നറിയിപ്പ്',
        'കോടതി നോട്ടീസ്',
        'അക്കൗണ്ട് ലോക്ക്',
        'സംശയാസ്പദ പ്രവർത്തനം',
        'സുരക്ഷാ മുന്നറിയിപ്പ്',
        // Urdu
        'فوری',
        'فوراً',
        'معطل',
        'کارروائی ضروری',
        'آپ کا اکاؤنٹ بند ہو جائے گا',
        'ابھی کلک کریں',
        'ابھی تصدیق کریں',
        'آخری نوٹس',
        'قانونی کارروائی',
        'جرمانہ',
        'آخری موقع',
        'فراڈ الرٹ',
        'عدالتی نوٹس',
        'اکاؤنٹ لاک',
        'مشکوک سرگرمی',
        'سیکیورٹی الرٹ',
        // Assamese
        'জৰুৰী',
        'তৎক্ষণাৎ',
        'স্থগিত',
        'ব্যৱস্থা প্ৰয়োজন',
        'আপোনাৰ একাউণ্ট বন্ধ হ\'ব',
        'এতিয়াই ক্লিক কৰক',
        'এতিয়াই যাচাই কৰক',
        'চূড়ান্ত জাননী',
        'আইনী ব্যৱস্থা',
        'জৰিমনা',
        'শেষ সুযোগ',
        'প্ৰতাৰণা সতৰ্কতা',
        'আদালতৰ জাননী',
        'একাউণ্ট লক',
        'সন্দেহজনক কাৰ্যকলাপ',
        'সুৰক্ষা সতৰ্কতা',
      ],
      bankKeywords: const [
        // English
        'kyc',
        'know your customer',
        'pan card',
        'aadhaar',
        'aadhar',
        'bank account',
        'net banking',
        'credit card',
        'debit card',
        'transaction failed',
        'upi',
        'paytm',
        'gpay',
        'phonepay',
        'neft',
        'imps',
        'ifsc',
        'loan approved',
        'emi',
        'insurance premium',
        'refund initiated',
        'cashback',
        'statement available',
        'account verification',
        'atm card',
        'bank verification',
        'kyc update',
        'payment declined',
        'transaction alert',
        // Hindi
        'केवाईसी',
        'पैन कार्ड',
        'आधार',
        'बैंक खाता',
        'नेट बैंकिंग',
        'क्रेडिट कार्ड',
        'डेबिट कार्ड',
        'लेनदेन विफल',
        'यूपीआई',
        'ऋण स्वीकृत',
        'ईएमआई',
        'बीमा प्रीमियम',
        'खाता सत्यापन',
        'एटीएम कार्ड',
        'केवाईसी अपडेट',
        'भुगतान अस्वीकृत',
        'लेनदेन अलर्ट',
        // Bengali
        'কেওয়াইসি',
        'প্যান কার্ড',
        'আধার',
        'ব্যাংক অ্যাকাউন্ট',
        'নেট ব্যাংকিং',
        'ক্রেডিট কার্ড',
        'ডেবিট কার্ড',
        'লেনদেন ব্যর্থ',
        'ঋণ অনুমোদিত',
        'ইএমআই',
        'বীমা প্রিমিয়াম',
        'অ্যাকাউন্ট যাচাইকরণ',
        'এটিএম কার্ড',
        'কেওয়াইসি আপডেট',
        'পেমেন্ট প্রত্যাখ্যান',
        'লেনদেন সতর্কতা',
        // Tamil
        'கேஒய்சி',
        'பான் கார்டு',
        'ஆதார்',
        'வங்கி கணக்கு',
        'நிகர வங்கி',
        'கடன் அட்டை',
        'டெபிட் கார்டு',
        'பரிவர்த்தனை தோல்வி',
        'கடன் அனுமதிக்கப்பட்டது',
        'ஈஎம்ஐ',
        'காப்பீட்டு பிரீமியம்',
        'கணக்கு சரிபார்ப்பு',
        'ஏடிஎம் கார்டு',
        'கேஒய்சி புதுப்பிப்பு',
        'பரிவர்த்தனை எச்சரிக்கை',
        // Telugu
        'కేవైసీ',
        'పాన్ కార్డ్',
        'ఆధార్',
        'బ్యాంక్ ఖాతా',
        'నెట్ బ్యాంకింగ్',
        'క్రెడిట్ కార్డ్',
        'డెబిట్ కార్డ్',
        'లావాదేవీ విఫలమైంది',
        'రుణం మంజూరు',
        'ఈఎంఐ',
        'బీమా ప్రీమియం',
        'ఖాతా ధృవీకరణ',
        'ఏటీఎం కార్డ్',
        'కేవైసీ అప్‌డేట్',
        'లావాదేవీ హెచ్చరిక',
        // Kannada
        'ಕೆವೈಸಿ',
        'ಪ್ಯಾನ್ ಕಾರ್ಡ್',
        'ಆಧಾರ್',
        'ಬ್ಯಾಂಕ್ ಖಾತೆ',
        'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
        'ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್',
        'ಡೆಬಿಟ್ ಕಾರ್ಡ್',
        'ವಹಿವಾಟು ವಿಫಲ',
        'ಸಾಲ ಅನುಮೋದಿಸಲಾಗಿದೆ',
        'ಇಎಂಐ',
        'ವಿಮಾ ಪ್ರೀಮಿಯಂ',
        'ಖಾತೆ ಪರಿಶೀಲನೆ',
        'ಎಟಿಎಂ ಕಾರ್ಡ್',
        'ಕೆವೈಸಿ ನವೀಕರಿಸಿ',
        'ವಹಿವಾಟು ಎಚ್ಚರಿಕೆ',
        // Malayalam
        'കെവൈസി',
        'പാൻ കാർഡ്',
        'ആധാർ',
        'ബാങ്ക് അക്കൗണ്ട്',
        'നെറ്റ് ബാങ്കിംഗ്',
        'ക്രെഡിറ്റ് കാർഡ്',
        'ഡെബിറ്റ് കാർഡ്',
        'ഇടപാട് പരാജയപ്പെട്ടു',
        'വായ്പ അനുമതി',
        'ഇഎംഐ',
        'ഇൻഷുറൻസ് പ്രീമിയം',
        'അക്കൗണ്ട് പരിശോധന',
        'എടിഎം കാർഡ്',
        'കെവൈസി അപ്‌ഡേറ്റ്',
        'ഇടപാട് മുന്നറിയിപ്പ്',
        // Urdu
        'کے وائی سی',
        'پین کارڈ',
        'آدھار',
        'بینک اکاؤنٹ',
        'نیٹ بینکنگ',
        'کریڈٹ کارڈ',
        'ڈیبٹ کارڈ',
        'ٹرانزیکشن ناکام',
        'قرض منظور',
        'ای ایم آئی',
        'بیمہ پریمیم',
        'اکاؤنٹ تصدیق',
        'اے ٹی ایم کارڈ',
        'کے وائی سی اپ ڈیٹ',
        'ٹرانزیکشن الرٹ',
        // Assamese
        'কেৱাইচি',
        'পেন কাৰ্ড',
        'আধাৰ',
        'বেংক একাউণ্ট',
        'নেট বেংকিং',
        'ক্ৰেডিট কাৰ্ড',
        'ডেবিট কাৰ্ড',
        'লেনদেন বিফল',
        'ঋণ অনুমোদন',
        'ইএমআই',
        'বীমা প্ৰিমিয়াম',
        'একাউণ্ট যাচাই',
        'এটিএম কাৰ্ড',
        'কেৱাইচি আপডেট',
        'লেনদেন সতৰ্কতা',
      ],
      suspectSenderPatterns: const [
        'secure',
        'alert',
        'verify',
        'support',
        'help-desk',
        'notice',
        'service',
        'info',
        'update',
        'security',
        'admin',
        'notification',
      ],
      otpKeywords: const [
        // English
        'otp',
        'one time password',
        'verification code',
        'security code',
        'login code',
        'authentication code',
        'use this code',
        'do not share this code',
        'password reset code',
        // Hindi
        'ओटीपी',
        'एक बार का पासवर्ड',
        'सत्यापन कोड',
        'सुरक्षा कोड',
        'लॉगिन कोड',
        'प्रमाणीकरण कोड',
        'इस कोड को साझा न करें',
        'पासवर्ड रीसेट कोड',
        // Bengali
        'ওটিপি',
        'একবারের পাসওয়ার্ড',
        'যাচাইকরণ কোড',
        'নিরাপত্তা কোড',
        'লগইন কোড',
        'প্রমাণীকরণ কোড',
        'এই কোড কারো সাথে শেয়ার করবেন না',
        // Tamil
        'ஒடிபி',
        'ஒரு முறை கடவுச்சொல்',
        'சரிபார்ப்பு குறியீடு',
        'பாதுகாப்பு குறியீடு',
        'உள்நுழைவு குறியீடு',
        'இந்த குறியீட்டை பகிர வேண்டாம்',
        // Telugu
        'ఒటిపి',
        'ఒకసారి పాస్‌వర్డ్',
        'ధృవీకరణ కోడ్',
        'భద్రత కోడ్',
        'లాగిన్ కోడ్',
        'ఈ కోడ్ పంచుకోవద్దు',
        // Kannada
        'ಒಟಿಪಿ',
        'ಒಂದು ಬಾರಿ ಪಾಸ್‌ವರ್ಡ್',
        'ಪರಿಶೀಲನೆ ಕೋಡ್',
        'ಭದ್ರತಾ ಕೋಡ್',
        'ಲಾಗಿನ್ ಕೋಡ್',
        'ಈ ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ',
        // Malayalam
        'ഒടിപി',
        'ഒറ്റത്തവണ പാസ്‌വേഡ്',
        'സ്ഥിരീകരണ കോഡ്',
        'സുരക്ഷാ കോഡ്',
        'ലോഗിൻ കോഡ്',
        'ഈ കോഡ് പങ്കിടരുത്',
        // Urdu
        'او ٹی پی',
        'یک وقتی پاس ورڈ',
        'توثیق کوڈ',
        'سیکیورٹی کوڈ',
        'لاگ ان کوڈ',
        'یہ کوڈ کسی کو نہ بتائیں',
        // Assamese
        'অটিপি',
        'এককালীন পাছৱৰ্ড',
        'যাচাই কোড',
        'সুৰক্ষা কোড',
        'লগইন কোড',
        'এই কোড কাকো নিদিব',
      ],
      paymentRequestKeywords: const [
        // English
        'pay now',
        'send money',
        'transfer immediately',
        'upi request',
        'approve payment',
        'payment link',
        'complete payment',
        'collect request',
        'request received',
        'upi collect',
        'pending payment',
        // Hindi
        'अभी भुगतान करें',
        'पैसे भेजें',
        'तुरंत स्थानांतरित करें',
        'यूपीआई अनुरोध',
        'भुगतान स्वीकृत करें',
        'भुगतान लिंक',
        'भुगतान पूरा करें',
        'संग्रह अनुरोध',
        'लंबित भुगतान',
        // Bengali
        'এখনই পরিশোধ করুন',
        'টাকা পাঠান',
        'তাৎক্ষণিক স্থানান্তর',
        'ইউপিআই অনুরোধ',
        'পেমেন্ট অনুমোদন করুন',
        'পেমেন্ট লিংক',
        'পেমেন্ট সম্পূর্ণ করুন',
        'বকেয়া পেমেন্ট',
        // Tamil
        'இப்போது பணம் செலுத்துங்கள்',
        'பணம் அனுப்புங்கள்',
        'உடனடியாக மாற்றுங்கள்',
        'யுபிஐ கோரிக்கை',
        'கட்டணத்தை அங்கீகரிக்கவும்',
        'கட்டண இணைப்பு',
        'கட்டணத்தை முடிக்கவும்',
        'நிலுவை கட்டணம்',
        // Telugu
        'ఇప్పుడే చెల్లించండి',
        'డబ్బు పంపండి',
        'వెంటనే బదిలీ చేయండి',
        'యూపీఐ అభ్యర్థన',
        'చెల్లింపు అనుమతించండి',
        'చెల్లింపు లింక్',
        'చెల్లింపు పూర్తి చేయండి',
        'పెండింగ్ చెల్లింపు',
        // Kannada
        'ಈಗ ಪಾವತಿ ಮಾಡಿ',
        'ಹಣ ಕಳುಹಿಸಿ',
        'ತಕ್ಷಣ ವರ್ಗಾಯಿಸಿ',
        'ಯುಪಿಐ ವಿನಂತಿ',
        'ಪಾವತಿ ಅನುಮೋದಿಸಿ',
        'ಪಾವತಿ ಲಿಂಕ್',
        'ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ',
        'ಬಾಕಿ ಪಾವತಿ',
        // Malayalam
        'ഇപ്പോൾ പണം അടക്കുക',
        'പണം അയക്കുക',
        'ഉടൻ കൈമാറ്റം ചെയ്യുക',
        'യുപിഐ അഭ്യർത്ഥന',
        'പേയ്‌മെന്റ് അംഗീകരിക്കുക',
        'പേയ്‌മെന്റ് ലിങ്ക്',
        'പേയ്‌മെന്റ് പൂർത്തിയാക്കുക',
        'തീർക്കേണ്ട പണം',
        // Urdu
        'ابھی ادائیگی کریں',
        'پیسے بھیجیں',
        'فوری منتقلی',
        'یو پی آئی درخواست',
        'ادائیگی کی منظوری',
        'پیمنٹ لنک',
        'ادائیگی مکمل کریں',
        'زیر التواء ادائیگی',
        // Assamese
        'এতিয়াই পৰিশোধ কৰক',
        'টকা পঠাওক',
        'তৎকালে স্থানান্তৰ কৰক',
        'ইউপিআই অনুৰোধ',
        'পেমেন্ট অনুমোদন কৰক',
        'পেমেন্ট লিংক',
        'পেমেন্ট সম্পূৰ্ণ কৰক',
        'বাকী পেমেন্ট',
      ],
      rewardScamKeywords: const [
        // English
        'you have won',
        'congratulations winner',
        'lottery',
        'jackpot',
        'claim prize',
        'free reward',
        'gift voucher',
        'lucky draw',
        'winner selected',
        'claim now',
        // Hindi
        'आपने जीता',
        'बधाई हो विजेता',
        'लॉटरी',
        'जैकपॉट',
        'इनाम का दावा करें',
        'मुफ्त उपहार',
        'उपहार वाउचर',
        'भाग्यशाली ड्रा',
        'विजेता चुना गया',
        'अभी दावा करें',
        // Bengali
        'আপনি জিতেছেন',
        'অভিনন্দন বিজয়ী',
        'লটারি',
        'জ্যাকপট',
        'পুরস্কার দাবি করুন',
        'বিনামূল্যে পুরস্কার',
        'গিফট ভাউচার',
        'লাকি ড্র',
        'বিজয়ী নির্বাচিত',
        'এখনই দাবি করুন',
        // Tamil
        'நீங்கள் வென்றீர்கள்',
        'வாழ்த்துக்கள் வெற்றியாளர்',
        'லாட்டரி',
        'ஜாக்பாட்',
        'பரிசு கோரவும்',
        'இலவச பரிசு',
        'பரிசு சீட்டு',
        'அதிர்ஷ்ட குலுக்கல்',
        'வெற்றியாளர் தேர்ந்தெடுக்கப்பட்டார்',
        'இப்போது கோரவும்',
        // Telugu
        'మీరు గెలిచారు',
        'అభినందనలు విజేత',
        'లాటరీ',
        'జాక్‌పాట్',
        'బహుమతి క్లెయిమ్ చేయండి',
        'ఉచిత బహుమతి',
        'గిఫ్ట్ వోచర్',
        'లక్కీ డ్రా',
        'విజేత ఎంపికయ్యారు',
        'ఇప్పుడే క్లెయిమ్ చేయండి',
        // Kannada
        'ನೀವು ಗೆದ್ದಿದ್ದೀರಿ',
        'ಅಭಿನಂದನೆ ವಿಜೇತ',
        'ಲಾಟರಿ',
        'ಜಾಕ್‌ಪಾಟ್',
        'ಬಹುಮಾನ ಕ್ಲೇಮ್ ಮಾಡಿ',
        'ಉಚಿತ ಉಡುಗೊರೆ',
        'ಗಿಫ್ಟ್ ವೌಚರ್',
        'ಲಕ್ಕಿ ಡ್ರಾ',
        'ವಿಜೇತ ಆಯ್ಕೆಯಾಗಿದ್ದಾರೆ',
        'ಈಗ ಕ್ಲೇಮ್ ಮಾಡಿ',
        // Malayalam
        'നിങ്ങൾ ജയിച്ചു',
        'അഭിനന്ദനങ്ങൾ വിജയി',
        'ലോട്ടറി',
        'ജാക്ക്‌പോട്ട്',
        'സമ്മാനം ക്ലെയിം ചെയ്യുക',
        'സൗജന്യ സമ്മാനം',
        'ഗിഫ്റ്റ് വൗച്ചർ',
        'ലക്കി ഡ്രോ',
        'വിജയി തിരഞ്ഞെടുത്തു',
        'ഇപ്പോൾ ക്ലെയിം ചെയ്യുക',
        // Urdu
        'آپ نے جیت لیا',
        'مبارکباد فاتح',
        'لاٹری',
        'جیک پاٹ',
        'انعام کا دعوی کریں',
        'مفت انعام',
        'گفٹ وائوچر',
        'لکی ڈرا',
        'فاتح منتخب',
        'ابھی دعوی کریں',
        // Assamese
        'আপুনি জিকিছে',
        'অভিনন্দন বিজয়ী',
        'লটাৰী',
        'জেকপট',
        'পুৰস্কাৰ দাবী কৰক',
        'বিনামূলীয়া পুৰস্কাৰ',
        'গিফট ভাউচাৰ',
        'লাকী ড্ৰ',
        'বিজয়ী নিৰ্বাচিত',
        'এতিয়াই দাবী কৰক',
      ],
      parcelScamKeywords: const [
        // English
        'parcel delivery',
        'shipment held',
        'delivery failed',
        'customs clearance',
        'track parcel',
        'delivery charge',
        'package pending',
        'courier service',
        'delivery attempt',
        'update delivery address',
        // Hindi
        'पार्सल डिलीवरी',
        'शिपमेंट रोका गया',
        'डिलीवरी विफल',
        'सीमा शुल्क मंजूरी',
        'पार्सल ट्रैक करें',
        'डिलीवरी शुल्क',
        'पैकेज लंबित',
        'कूरियर सेवा',
        'डिलीवरी प्रयास',
        'डिलीवरी पता अपडेट करें',
        // Bengali
        'পার্সেল ডেলিভারি',
        'শিপমেন্ট আটকানো',
        'ডেলিভারি ব্যর্থ',
        'কাস্টমস ছাড়পত্র',
        'পার্সেল ট্র্যাক করুন',
        'ডেলিভারি চার্জ',
        'প্যাকেজ অপেক্ষমাণ',
        'কুরিয়ার সার্ভিস',
        'ডেলিভারি প্রচেষ্টা',
        'ডেলিভারি ঠিকানা আপডেট করুন',
        // Tamil
        'பார்சல் டெலிவரி',
        'ஷிப்மென்ட் நிறுத்தப்பட்டது',
        'டெலிவரி தோல்வி',
        'சுங்க அனுமதி',
        'பார்சல் கண்காணிக்கவும்',
        'டெலிவரி கட்டணம்',
        'தொகுப்பு நிலுவையில்',
        'கூரியர் சேவை',
        'டெலிவரி முயற்சி',
        'டெலிவரி முகவரி புதுப்பிக்கவும்',
        // Telugu
        'పార్సెల్ డెలివరీ',
        'షిప్‌మెంట్ ఆపబడింది',
        'డెలివరీ విఫలమైంది',
        'కస్టమ్స్ క్లియరెన్స్',
        'పార్సెల్ ట్రాక్ చేయండి',
        'డెలివరీ చార్జ్',
        'ప్యాకేజ్ పెండింగ్',
        'కూరియర్ సేవ',
        'డెలివరీ ప్రయత్నం',
        'డెలివరీ చిరునామా అప్‌డేట్ చేయండి',
        // Kannada
        'ಪಾರ್ಸೆಲ್ ಡೆಲಿವರಿ',
        'ಶಿಪ್‌ಮೆಂಟ್ ತಡೆಹಿಡಿಯಲಾಗಿದೆ',
        'ಡೆಲಿವರಿ ವಿಫಲ',
        'ಕಸ್ಟಮ್ಸ್ ಕ್ಲಿಯರೆನ್ಸ್',
        'ಪಾರ್ಸೆಲ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
        'ಡೆಲಿವರಿ ಶುಲ್ಕ',
        'ಪ್ಯಾಕೇಜ್ ಬಾಕಿ',
        'ಕೊರಿಯರ್ ಸೇವೆ',
        'ಡೆಲಿವರಿ ಪ್ರಯತ್ನ',
        'ಡೆಲಿವರಿ ವಿಳಾಸ ನವೀಕರಿಸಿ',
        // Malayalam
        'പാഴ്‌സൽ ഡെലിവറി',
        'ഷിപ്‌മെന്റ് തടഞ്ഞു',
        'ഡെലിവറി പരാജയപ്പെട്ടു',
        'കസ്റ്റംസ് ക്ലിയറൻസ്',
        'പാഴ്‌സൽ ട്രാക്ക് ചെയ്യുക',
        'ഡെലിവറി ചാർജ്',
        'പാക്കേജ് കാത്തിരിക്കുന്നു',
        'കൂറിയർ സേവനം',
        'ഡെലിവറി ശ്രമം',
        'ഡെലിവറി വിലാസം അപ്‌ഡേറ്റ് ചെയ്യുക',
        // Urdu
        'پارسل ڈیلیوری',
        'شپمنٹ روکا گیا',
        'ڈیلیوری ناکام',
        'کسٹمز کلیئرنس',
        'پارسل ٹریک کریں',
        'ڈیلیوری چارج',
        'پیکج زیر التواء',
        'کوریئر سروس',
        'ڈیلیوری کی کوشش',
        'ڈیلیوری پتہ اپ ڈیٹ کریں',
        // Assamese
        'পাৰ্চেল ডেলিভাৰী',
        'শিপমেন্ট আটকোৱা হৈছে',
        'ডেলিভাৰী বিফল',
        'কাষ্টমছ ক্লিয়াৰেন্স',
        'পাৰ্চেল ট্ৰেক কৰক',
        'ডেলিভাৰী চাৰ্জ',
        'পেকেজ বাকী',
        'কুৰিয়াৰ সেৱা',
        'ডেলিভাৰী প্ৰচেষ্টা',
        'ডেলিভাৰী ঠিকনা আপডেট কৰক',
      ],
      cryptoScamKeywords: const [
        // English
        'bitcoin',
        'crypto investment',
        'double your crypto',
        'ethereum',
        'usdt',
        'crypto wallet',
        'investment opportunity',
        'guaranteed return',
        'trading signal',
        'crypto profit',
        // Hindi
        'बिटकॉइन',
        'क्रिप्टो निवेश',
        'अपना क्रिप्टो दोगुना करें',
        'एथेरियम',
        'यूएसडीटी',
        'क्रिप्टो वॉलेट',
        'निवेश का अवसर',
        'गारंटीड रिटर्न',
        'ट्रेडिंग सिग्नल',
        'क्रिप्टो लाभ',
        // Bengali
        'বিটকয়েন',
        'ক্রিপ্টো বিনিয়োগ',
        'আপনার ক্রিপ্টো দ্বিগুণ করুন',
        'ইথেরিয়াম',
        'ইউএসডিটি',
        'ক্রিপ্টো ওয়ালেট',
        'বিনিয়োগের সুযোগ',
        'নিশ্চিত রিটার্ন',
        'ট্রেডিং সিগন্যাল',
        'ক্রিপ্টো লাভ',
        // Tamil
        'பிட்காயின்',
        'கிரிப்டோ முதலீடு',
        'உங்கள் கிரிப்டோவை இரட்டிப்பாக்குங்கள்',
        'எதீரியம்',
        'யூஎஸ்டிடி',
        'கிரிப்டோ பணப்பை',
        'முதலீட்டு வாய்ப்பு',
        'உறுதியான வருமானம்',
        'வர்த்தக சமிக்ஞை',
        'கிரிப்டோ லாபம்',
        // Telugu
        'బిట్‌కాయిన్',
        'క్రిప్టో పెట్టుబడి',
        'మీ క్రిప్టోను రెట్టింపు చేయండి',
        'ఇథేరియం',
        'యుఎస్‌డిటి',
        'క్రిప్టో వాలెట్',
        'పెట్టుబడి అవకాశం',
        'హామీ రిటర్న్',
        'ట్రేడింగ్ సిగ్నల్',
        'క్రిప్టో లాభం',
        // Kannada
        'ಬಿಟ್‌ಕಾಯಿನ್',
        'ಕ್ರಿಪ್ಟೋ ಹೂಡಿಕೆ',
        'ನಿಮ್ಮ ಕ್ರಿಪ್ಟೋ ಡಬಲ್ ಮಾಡಿ',
        'ಇಥೀರಿಯಂ',
        'ಯುಎಸ್‌ಡಿಟಿ',
        'ಕ್ರಿಪ್ಟೋ ವಾಲೆಟ್',
        'ಹೂಡಿಕೆ ಅವಕಾಶ',
        'ಗ್ಯಾರಂಟಿ ರಿಟರ್ನ್',
        'ಟ್ರೇಡಿಂಗ್ ಸಿಗ್ನಲ್',
        'ಕ್ರಿಪ್ಟೋ ಲಾಭ',
        // Malayalam
        'ബിറ്റ്‌കോയിൻ',
        'ക്രിപ്‌റ്റോ നിക്ഷേപം',
        'നിങ്ങളുടെ ക്രിപ്‌റ്റോ ഇരട്ടിയാക്കുക',
        'ഇഥേരിയം',
        'യുഎസ്‌ഡിടി',
        'ക്രിപ്‌റ്റോ വാലറ്റ്',
        'നിക്ഷേപ അവസരം',
        'ഉറപ്പ് നൽകിയ വരുമാനം',
        'ട്രേഡിംഗ് സിഗ്നൽ',
        'ക്രിപ്‌റ്റോ ലാഭം',
        // Urdu
        'بٹ کوائن',
        'کرپٹو سرمایہ کاری',
        'اپنا کرپٹو دوگنا کریں',
        'ایتھیریم',
        'یو ایس ڈی ٹی',
        'کرپٹو والٹ',
        'سرمایہ کاری کا موقع',
        'گارنٹی شدہ واپسی',
        'ٹریڈنگ سگنل',
        'کرپٹو منافع',
        // Assamese
        'বিটকইন',
        'ক্ৰিপ্টো বিনিয়োগ',
        'আপোনাৰ ক্ৰিপ্টো দ্বিগুণ কৰক',
        'ইথেৰিয়াম',
        'ইউএছডিটি',
        'ক্ৰিপ্টো ৱালেট',
        'বিনিয়োগৰ সুযোগ',
        'গেৰেণ্টিড ৰিটাৰ্ণ',
        'ট্ৰেডিং চিগনেল',
        'ক্ৰিপ্টো লাভ',
      ],
    );
  }

  factory DetectorConfig.fromJson(Map<String, dynamic> json) {
    final defaults = DetectorConfig.defaults();
    return DetectorConfig(
      thresholdMedium:
          (json['thresholdMedium'] as num?)?.toDouble() ?? defaults.thresholdMedium,
      thresholdHigh:
          (json['thresholdHigh'] as num?)?.toDouble() ?? defaults.thresholdHigh,
      weightShortUrl:
          (json['weightShortUrl'] as num?)?.toDouble() ?? defaults.weightShortUrl,
      weightOtp: (json['weightOtp'] as num?)?.toDouble() ?? defaults.weightOtp,
      weightUrgency:
          (json['weightUrgency'] as num?)?.toDouble() ?? defaults.weightUrgency,
      weightBankKeyword:
          (json['weightBankKeyword'] as num?)?.toDouble() ?? defaults.weightBankKeyword,
      weightSuspectSender:
          (json['weightSuspectSender'] as num?)?.toDouble() ?? defaults.weightSuspectSender,
      weightInCallOtpBoost:
          (json['weightInCallOtpBoost'] as num?)?.toDouble() ?? defaults.weightInCallOtpBoost,
      weightPaymentRequest:
          (json['weightPaymentRequest'] as num?)?.toDouble() ?? defaults.weightPaymentRequest,
      weightRewardScam:
          (json['weightRewardScam'] as num?)?.toDouble() ?? defaults.weightRewardScam,
      weightParcelScam:
          (json['weightParcelScam'] as num?)?.toDouble() ?? defaults.weightParcelScam,
      weightCryptoScam:
          (json['weightCryptoScam'] as num?)?.toDouble() ?? defaults.weightCryptoScam,
      shortUrlDomains: (json['shortUrlDomains'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          defaults.shortUrlDomains,
      urgencyKeywords: (json['urgencyKeywords'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          defaults.urgencyKeywords,
      bankKeywords: (json['bankKeywords'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          defaults.bankKeywords,
      suspectSenderPatterns:
          (json['suspectSenderPatterns'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              defaults.suspectSenderPatterns,
      otpKeywords: (json['otpKeywords'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          defaults.otpKeywords,
      paymentRequestKeywords:
          (json['paymentRequestKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              defaults.paymentRequestKeywords,
      rewardScamKeywords:
          (json['rewardScamKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              defaults.rewardScamKeywords,
      parcelScamKeywords:
          (json['parcelScamKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              defaults.parcelScamKeywords,
      cryptoScamKeywords:
          (json['cryptoScamKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              defaults.cryptoScamKeywords,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'thresholdMedium': thresholdMedium,
      'thresholdHigh': thresholdHigh,
      'weightShortUrl': weightShortUrl,
      'weightOtp': weightOtp,
      'weightUrgency': weightUrgency,
      'weightBankKeyword': weightBankKeyword,
      'weightSuspectSender': weightSuspectSender,
      'weightInCallOtpBoost': weightInCallOtpBoost,
      'weightPaymentRequest': weightPaymentRequest,
      'weightRewardScam': weightRewardScam,
      'weightParcelScam': weightParcelScam,
      'weightCryptoScam': weightCryptoScam,
      'shortUrlDomains': shortUrlDomains,
      'urgencyKeywords': urgencyKeywords,
      'bankKeywords': bankKeywords,
      'suspectSenderPatterns': suspectSenderPatterns,
      'otpKeywords': otpKeywords,
      'paymentRequestKeywords': paymentRequestKeywords,
      'rewardScamKeywords': rewardScamKeywords,
      'parcelScamKeywords': parcelScamKeywords,
      'cryptoScamKeywords': cryptoScamKeywords,
    };
  }
}
