class DetectorConfig {
  final double thresholdMedium;
  final double thresholdHigh;

  final double weightShortUrl;
  final double weightOtp;
  final double weightUrgency;
  final double weightBankKeyword;
  final double weightSuspectSender;
  final double weightInCallOtpBoost;

  // Additional per-signal weights for specific scam patterns.
  final double weightPaymentRequest;
  final double weightRewardScam;
  final double weightParcelScam;
  final double weightCryptoScam;

  final List<String> shortUrlDomains;
  final List<String> urgencyKeywords;
  final List<String> bankKeywords;
  final List<String> suspectSenderPatterns;
  final List<String> otpKeywords;
  final List<String> paymentRequestKeywords;
  final List<String> rewardScamKeywords;
  final List<String> parcelScamKeywords;
  final List<String> cryptoScamKeywords;

  const DetectorConfig({
    required this.thresholdMedium,
    required this.thresholdHigh,
    required this.weightShortUrl,
    required this.weightOtp,
    required this.weightUrgency,
    required this.weightBankKeyword,
    required this.weightSuspectSender,
    required this.weightInCallOtpBoost,
    required this.weightPaymentRequest,
    required this.weightRewardScam,
    required this.weightParcelScam,
    required this.weightCryptoScam,
    required this.shortUrlDomains,
    required this.urgencyKeywords,
    required this.bankKeywords,
    required this.suspectSenderPatterns,
    required this.otpKeywords,
    required this.paymentRequestKeywords,
    required this.rewardScamKeywords,
    required this.parcelScamKeywords,
    required this.cryptoScamKeywords,
  });

  factory DetectorConfig.defaults() {
    return DetectorConfig(
      thresholdMedium: 0.4,
      thresholdHigh: 0.7,
      weightShortUrl: 0.25,
      weightOtp: 0.25,
      weightUrgency: 0.20,
      weightBankKeyword: 0.20,
      weightSuspectSender: 0.10,
      weightInCallOtpBoost: 0.35,
      weightPaymentRequest: 0.20,
      weightRewardScam: 0.15,
      weightParcelScam: 0.15,
      weightCryptoScam: 0.15,
      shortUrlDomains: const [
        'bit.ly',
        'tinyurl.com',
        'goo.gl',
        't.co',
        'ow.ly',
        'is.gd',
        'buff.ly',
        'adf.ly',
        'short.io',
        'rb.gy',
        'cutt.ly',
        'tiny.cc',
        'snip.ly',
        'rebrand.ly',
        'soo.gd',
        'lnkd.in',
        'bl.ink',
        'shorte.st',
        'clk.im',
        'mcaf.ee',
      ],
      urgencyKeywords: const [
        'urgent',
        'immediately',
        'suspended',
        'blocked',
        'action required',
        'your account will be',
        'click now',
        'verify now',
        'limited time',
        'expire',
        'final notice',
        'legal action',
        'arrested',
        'penalty',
        'act now',
        'last chance',
        'warning:',
        'alert:',
        'fraud alert',
        'court notice',
        'tax penalty',
        'customs issue',
        'delivery failed',
        'payment pending',
        'security alert',
        'unauthorized access',
        'update immediately',
        'account locked',
        'suspicious activity detected',
        // Hindi
        'तुरंत',
        'अभी करें',
        'खाता बंद हो जाएगा',
        'तत्काल',
        'अंतिम नोटिस',
        'कानूनी कार्रवाई',
        'जुर्माना',
        'चेतावनी:',
        'सुरक्षा अलर्ट',
        'खाता लॉक',
        'संदिग्ध गतिविधि',
        'धोखाधड़ी अलर्ट',
        'गिरफ्तार',
        'अंतिम मौका',
        // Tamil
        'அவசரம்',
        'உடனே',
        'உங்கள் கணக்கு நிறுத்தப்படும்',
        'இறுதி அறிவிப்பு',
        'சட்ட நடவடிக்கை',
        'எச்சரிக்கை:',
        'மோசடி எச்சரிக்கை',
        'கணக்கு பூட்டப்பட்டது',
        'பாதுகாப்பு எச்சரிக்கை',
        'சந்தேகமான செயல்பாடு',
        'கடைசி வாய்ப்பு',
        'உடனடியாக',
        // Bengali
        'জরুরি',
        'অবিলম্বে',
        'আপনার অ্যাকাউন্ট বন্ধ হয়ে যাবে',
        'চূড়ান্ত নোটিশ',
        'আইনি পদক্ষেপ',
        'সতর্কতা:',
        'জালিয়াতি সতর্কতা',
        'অ্যাকাউন্ট লক',
        'নিরাপত্তা সতর্কতা',
        'সন্দেহজনক কার্যকলাপ',
        'শেষ সুযোগ',
      ],
      bankKeywords: const [
        'kyc',
        'know your customer',
        'pan card',
        'aadhaar',
        'aadhar',
        'bank account',
        'net banking',
        'credit card',
        'debit card',
        'transaction failed',
        'upi',
        'paytm',
        'gpay',
        'phonepay',
        'neft',
        'imps',
        'ifsc',
        'loan approved',
        'emi',
        'insurance premium',
        'refund initiated',
        'cashback',
        'statement available',
        'account verification',
        'atm card',
        'bank verification',
        'kyc update',
        'payment declined',
        'transaction alert',
        // Hindi
        'केवाईसी',
        'बैंक खाता',
        'नेट बैंकिंग',
        'क्रेडिट कार्ड',
        'डेबिट कार्ड',
        'लेनदेन विफल',
        'ऋण स्वीकृत',
        'रिफंड',
        'एटीएम कार्ड',
        'बैंक सत्यापन',
        'भुगतान अस्वीकार',
        'खाता सत्यापन',
        // Tamil
        'வங்கி கணக்கு',
        'நிகர வங்கி',
        'கடன் அட்டை',
        'பற்று அட்டை',
        'பரிவர்த்தனை தோல்வி',
        'கடன் அனுமதிக்கப்பட்டது',
        'திரும்ப செலுத்துதல்',
        'ஏடிஎம்',
        'வங்கி சரிபார்ப்பு',
        'கணக்கு சரிபார்ப்பு',
        // Bengali
        'কেওয়াইসি',
        'ব্যাংক অ্যাকাউন্ট',
        'নেট ব্যাংকিং',
        'ক্রেডিট কার্ড',
        'ডেবিট কার্ড',
        'লেনদেন ব্যর্থ',
        'ঋণ অনুমোদিত',
        'রিফান্ড',
        'এটিএম কার্ড',
        'ব্যাংক যাচাই',
        'অ্যাকাউন্ট যাচাই',
      ],
      suspectSenderPatterns: const [
        'secure',
        'alert',
        'verify',
        'support',
        'help-desk',
        'notice',
        'service',
        'info',
        'update',
        'security',
        'admin',
        'notification',
      ],
      otpKeywords: const [
        'otp',
        'one time password',
        'verification code',
        'security code',
        'login code',
        'authentication code',
        'use this code',
        'do not share this code',
        'password reset code',
        // Hindi
        'ओटीपी',
        'सत्यापन कोड',
        'सुरक्षा कोड',
        'इस कोड को साझा न करें',
        'कोड किसी को न बताएं',
        // Tamil
        'ஓடிபி',
        'சரிபார்ப்பு குறியீடு',
        'பாதுகாப்பு குறியீடு',
        'இந்த குறியீட்டை யாரிடமும் பகிர வேண்டாம்',
        // Bengali
        'ওটিপি',
        'যাচাইকরণ কোড',
        'নিরাপত্তা কোড',
        'এই কোডটি কাউকে দেবেন না',
      ],
      paymentRequestKeywords: const [
        'pay now',
        'send money',
        'transfer immediately',
        'upi request',
        'approve payment',
        'payment link',
        'complete payment',
        'collect request',
        'request received',
        'upi collect',
        'pending payment',
        // Hindi
        'अभी भुगतान करें',
        'पैसे भेजें',
        'तुरंत ट्रांसफर',
        'भुगतान लिंक',
        'भुगतान स्वीकार करें',
        'लंबित भुगतान',
        // Tamil
        'இப்போதே செலுத்தவும்',
        'பணம் அனுப்பவும்',
        'உடனடியாக மாற்றவும்',
        'கட்டண இணைப்பு',
        'கட்டணம் ஒப்புக்கொள்ளவும்',
        // Bengali
        'এখনই পরিশোধ করুন',
        'টাকা পাঠান',
        'অবিলম্বে স্থানান্তর করুন',
        'পেমেন্ট লিংক',
        'পেমেন্ট অনুমোদন করুন',
      ],
      rewardScamKeywords: const [
        'you have won',
        'congratulations winner',
        'lottery',
        'jackpot',
        'claim prize',
        'free reward',
        'gift voucher',
        'lucky draw',
        'winner selected',
        'claim now',
        // Hindi
        'आपने जीता',
        'बधाई हो विजेता',
        'लॉटरी',
        'पुरस्कार का दावा करें',
        'मुफ्त इनाम',
        'भाग्यशाली ड्रा',
        'अभी दावा करें',
        // Tamil
        'நீங்கள் வென்றீர்கள்',
        'வாழ்த்துக்கள் வெற்றியாளர்',
        'லாட்டரி',
        'பரிசு கோரவும்',
        'இலவச பரிசு',
        'அதிர்ஷ்ட சீட்டு',
        // Bengali
        'আপনি জিতেছেন',
        'অভিনন்দন বিজয়ী',
        'লটারি',
        'পুরস্কার দাবি করুন',
        'বিনামূল্যে উপহার',
        'ভাগ্যবান ড্র',
      ],
      parcelScamKeywords: const [
        'parcel delivery',
        'shipment held',
        'delivery failed',
        'customs clearance',
        'track parcel',
        'delivery charge',
        'package pending',
        'courier service',
        'delivery attempt',
        'update delivery address',
        // Hindi
        'पार्सल डिलीवरी',
        'शिपमेंट रोका',
        'डिलीवरी विफल',
        'सीमा शुल्क',
        'डिलीवरी शुल्क',
        'पैकेज लंबित',
        'कूरियर सेवा',
        // Tamil
        'பார்சல் டெலிவரி',
        'ஷிப்மென்ட் நிறுத்தப்பட்டது',
        'டெலிவரி தோல்வி',
        'சுங்க வரி',
        'டெலிவரி கட்டணம்',
        'கூரியர் சேவை',
        // Bengali
        'পার্সেল ডেলিভারি',
        'শিপমেন্ট আটকানো',
        'ডেলিভারি ব্যর্থ',
        'কাস্টমস',
        'ডেলিভারি চার্জ',
        'কুরিয়ার সেবা',
      ],
      cryptoScamKeywords: const [
        'bitcoin',
        'crypto investment',
        'double your crypto',
        'ethereum',
        'usdt',
        'crypto wallet',
        'investment opportunity',
        'guaranteed return',
        'trading signal',
        'crypto profit',
        // Hindi
        'बिटकॉइन',
        'क्रिप्टो निवेश',
        'क्रिप्टो वॉलेट',
        'निवेश का अवसर',
        'गारंटीड रिटर्न',
        'ट्रेडिंग सिग्नल',
        // Tamil
        'பிட்காயின்',
        'கிரிப்டோ முதலீடு',
        'கிரிப்டோ வாலட்',
        'முதலீட்டு வாய்ப்பு',
        'உத்தரவாதமான வருமானம்',
        // Bengali
        'বিটকয়েন',
        'ক্রিপ্টো বিনিয়োগ',
        'ক্রিপ্টো ওয়ালেট',
        'বিনিয়োগের সুযোগ',
        'নিশ্চিত রিটার্ন',
      ],
    );
  }

  factory DetectorConfig.fromJson(Map<String, dynamic> json) {
    return DetectorConfig(
      thresholdMedium:
          (json['thresholdMedium'] as num?)?.toDouble() ?? 0.4,
      thresholdHigh: (json['thresholdHigh'] as num?)?.toDouble() ?? 0.7,
      weightShortUrl: (json['weightShortUrl'] as num?)?.toDouble() ?? 0.25,
      weightOtp: (json['weightOtp'] as num?)?.toDouble() ?? 0.25,
      weightUrgency: (json['weightUrgency'] as num?)?.toDouble() ?? 0.20,
      weightBankKeyword:
          (json['weightBankKeyword'] as num?)?.toDouble() ?? 0.20,
      weightSuspectSender:
          (json['weightSuspectSender'] as num?)?.toDouble() ?? 0.10,
      weightInCallOtpBoost:
          (json['weightInCallOtpBoost'] as num?)?.toDouble() ?? 0.35,
      weightPaymentRequest:
          (json['weightPaymentRequest'] as num?)?.toDouble() ?? 0.20,
      weightRewardScam:
          (json['weightRewardScam'] as num?)?.toDouble() ?? 0.15,
      weightParcelScam:
          (json['weightParcelScam'] as num?)?.toDouble() ?? 0.15,
      weightCryptoScam:
          (json['weightCryptoScam'] as num?)?.toDouble() ?? 0.15,
      shortUrlDomains: (json['shortUrlDomains'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [
            'bit.ly',
            'tinyurl.com',
            'goo.gl',
            't.co',
            'ow.ly',
            'is.gd',
            'buff.ly',
            'adf.ly',
            'short.io',
            'rb.gy',
            'cutt.ly',
            'tiny.cc',
            'snip.ly',
            'rebrand.ly',
            'soo.gd',
            'lnkd.in',
            'bl.ink',
            'shorte.st',
            'clk.im',
            'mcaf.ee',
          ],
      urgencyKeywords: (json['urgencyKeywords'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [
            'urgent',
            'immediately',
            'suspended',
            'blocked',
            'action required',
            'your account will be',
            'click now',
            'verify now',
            'limited time',
            'expire',
            'final notice',
            'legal action',
            'arrested',
            'penalty',
            'act now',
            'last chance',
            'warning:',
            'alert:',
            'fraud alert',
            'court notice',
            'tax penalty',
            'customs issue',
            'delivery failed',
            'payment pending',
            'security alert',
            'unauthorized access',
            'update immediately',
            'account locked',
            'suspicious activity detected',
          ],
      bankKeywords: (json['bankKeywords'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [
            'kyc',
            'know your customer',
            'pan card',
            'aadhaar',
            'aadhar',
            'bank account',
            'net banking',
            'credit card',
            'debit card',
            'transaction failed',
            'upi',
            'paytm',
            'gpay',
            'phonepay',
            'neft',
            'imps',
            'ifsc',
            'loan approved',
            'emi',
            'insurance premium',
            'refund initiated',
            'cashback',
            'statement available',
            'account verification',
            'atm card',
            'bank verification',
            'kyc update',
            'payment declined',
            'transaction alert',
          ],
      suspectSenderPatterns:
          (json['suspectSenderPatterns'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              const [
                'secure',
                'alert',
                'verify',
                'support',
                'help-desk',
                'notice',
                'service',
                'info',
                'update',
                'security',
                'admin',
                'notification',
              ],
      otpKeywords: (json['otpKeywords'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          const [
            'otp',
            'one time password',
            'verification code',
            'security code',
            'login code',
            'authentication code',
            'use this code',
            'do not share this code',
            'password reset code',
          ],
      paymentRequestKeywords:
          (json['paymentRequestKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              const [
                'pay now',
                'send money',
                'transfer immediately',
                'upi request',
                'approve payment',
                'payment link',
                'complete payment',
                'collect request',
                'request received',
                'upi collect',
                'pending payment',
              ],
      rewardScamKeywords:
          (json['rewardScamKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              const [
                'you have won',
                'congratulations winner',
                'lottery',
                'jackpot',
                'claim prize',
                'free reward',
                'gift voucher',
                'lucky draw',
                'winner selected',
                'claim now',
              ],
      parcelScamKeywords:
          (json['parcelScamKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              const [
                'parcel delivery',
                'shipment held',
                'delivery failed',
                'customs clearance',
                'track parcel',
                'delivery charge',
                'package pending',
                'courier service',
                'delivery attempt',
                'update delivery address',
              ],
      cryptoScamKeywords:
          (json['cryptoScamKeywords'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              const [
                'bitcoin',
                'crypto investment',
                'double your crypto',
                'ethereum',
                'usdt',
                'crypto wallet',
                'investment opportunity',
                'guaranteed return',
                'trading signal',
                'crypto profit',
              ],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'thresholdMedium': thresholdMedium,
      'thresholdHigh': thresholdHigh,
      'weightShortUrl': weightShortUrl,
      'weightOtp': weightOtp,
      'weightUrgency': weightUrgency,
      'weightBankKeyword': weightBankKeyword,
      'weightSuspectSender': weightSuspectSender,
      'weightInCallOtpBoost': weightInCallOtpBoost,
      'weightPaymentRequest': weightPaymentRequest,
      'weightRewardScam': weightRewardScam,
      'weightParcelScam': weightParcelScam,
      'weightCryptoScam': weightCryptoScam,
      'shortUrlDomains': shortUrlDomains,
      'urgencyKeywords': urgencyKeywords,
      'bankKeywords': bankKeywords,
      'suspectSenderPatterns': suspectSenderPatterns,
      'otpKeywords': otpKeywords,
      'paymentRequestKeywords': paymentRequestKeywords,
      'rewardScamKeywords': rewardScamKeywords,
      'parcelScamKeywords': parcelScamKeywords,
      'cryptoScamKeywords': cryptoScamKeywords,
    };
  }
}

